# Grafana credentials — K8s Secret
# IMPORTANTE: Cambiar los valores antes de despliegue en producción.
# Generar valores: echo -n "tu-password" | base64
#
# Valores actuales (solo desarrollo local):
#   admin-user:     admin
#   admin-password: admin
#
# Para producción:
#   kubectl create secret generic grafana-credentials \
#     --from-literal=admin-user=admin \
#     --from-literal=admin-password=TU_PASSWORD_SEGURO \
#     --namespace=claudescale

apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: claudescale
  labels:
    app: grafana
type: Opaque
data:
  # base64("admin")
  admin-user: YWRtaW4=
  # base64("admin") — CAMBIAR EN PRODUCCIÓN
  admin-password: YWRtaW4=
